USE bdFiliados2021

SELECT * FROM dbo.[Filiados_PTC (1)]

--19
UPDATE dbo.[Filiados_PTC (1)]
SET SIGLA_DO_PARTIDO ='PT'
WHERE CODIGO_DO_MUNICIPIO = '36471'

--20
 UPDATE dbo.[Filiados_PTC (1)]
SET SIGLA_DO_PARTIDO ='PMDB'
WHERE CODIGO_DO_MUNICIPIO = '38490'

--21
 UPDATE dbo.[Filiados_PTC (1)]
SET SIGLA_DO_PARTIDO ='PC'
WHERE NOME_DO_MUNICIPIO = 'SANTANÓPOLIS'

--22
 UPDATE dbo.[Filiados_PTC (1)]
SET SIGLA_DO_PARTIDO ='PV', NOME_DO_PARTIDO = 'Partido Verde dos Filiados'
WHERE NOME_DO_MUNICIPIO = 'SAO FELIX'

--23
 UPDATE dbo.[Filiados_PTC (1)]
SET SIGLA_DO_PARTIDO = 'PSDB', NOME_DO_PARTIDO = 'Partido Trabalhista Cristão para Partido da Social Democracia Brasileira'
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA'

--24
UPDATE dbo.[Filiados_PTC (1)]
SET NOME_DO_FILIADO = 'JORGE LUIS MAGALHÃES DOS SANTOS'
WHERE NOME_DO_FILIADO = 'JORGE LUIS FERREIRA DOS SANTOS'

--25
UPDATE dbo.[Filiados_PTC (1)]
SET NOME_DO_FILIADO = 'RENATA XAVIER RODRIGUE.'
WHERE NOME_DO_FILIADO = 'BENTA XAVIER RODRIGUES'

--26
UPDATE dbo.[Filiados_PTC (1)]
SET NOME_DO_FILIADO = 'NOEL LEITE DA SILVA'
WHERE NOME_DO_FILIADO = 'NOE LEITE DA SILVA'

--27
UPDATE dbo.[Filiados_PTC (1)]
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'JOSIENE ANDRADE DE SOUZA'

--28
UPDATE dbo.[Filiados_PTC (1)]
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO ='ELIEL ALMEIDA SILVA'

--29
UPDATE dbo.[Filiados_PTC (1)]
SET SITUACAO_DO_REGISTRO = 'DESFILIADO'
WHERE NOME_DO_FILIADO = 'ALINE DE SOUZA'

--30
ALTER TABLE dbo.[Filiados_PTC (1)] ADD SEXO CHAR 